import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import type { App } from 'vue'

import {
  faBrain,
  faWrench,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faCheck,
  faSpinner,
  faXmark,
  faPaperPlane,
  faAlignLeft,
  faBars,
  faPlus,
  faTrashCan,
  faMagnifyingGlassPlus,
  faMagnifyingGlassMinus,
  faExpand,
  faDownload,
  faICursor,
  faRotateRight,
  faTriangleExclamation,
  faCircleInfo,
  faFileLines,
  faStop,
  faUserGear,
  faBolt,
  faThumbtack,
  faHouse,
  faKey,
  faRightFromBracket,
  faMemory,
  faGauge,
  faUser,
  faComments,
  faClock,
  faGear,
  faPalette,
  faSun,
  faMoon,
  faDesktop,
  faPaw,
  faMusic,
  faFile
} from '@fortawesome/free-solid-svg-icons'

import {
  faCopy,
  faPenToSquare,
  faFolder
} from '@fortawesome/free-regular-svg-icons'

library.add(
  faBrain,
  faWrench,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faCheck,
  faSpinner,
  faXmark,
  faPaperPlane,
  faAlignLeft,
  faBars,
  faPlus,
  faTrashCan,
  faMagnifyingGlassPlus,
  faMagnifyingGlassMinus,
  faExpand,
  faDownload,
  faICursor,
  faRotateRight,
  faTriangleExclamation,
  faCircleInfo,
  faFileLines,
  faStop,
  faUserGear,
  faBolt,
  faThumbtack,
  faHouse,
  faKey,
  faRightFromBracket,
  faMemory,
  faGauge,
  faUser,
  faComments,
  faClock,
  faGear,
  faPalette,
  faSun,
  faMoon,
  faDesktop,
  faPaw,
  faMusic,
  faFile,
  faFolder,
  faCopy,
  faPenToSquare
)

export function registerFontAwesome(app: App) {
  app.component('FontAwesomeIcon', FontAwesomeIcon)
}
